version: '3'
services:
  server:
    image: "node:alpine"
    restart: "always"
    volumes:
      - .:/picluster
      - ./docker-compose.config.json:/picluster/config.json
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3003:3003"
    working_dir: /picluster
    command: ["sh", "-c", "set -e; apk add --no-cache git python make g++ docker procps; export PATH=/bin:$PATH; npm install --production; cd /picluster/server; node server.js &; cd /picluster/agent; node agent.js; cd /picluster/web; node webconsole.js"]
