version: '3'
services:
  server:
    image: "node:alpine"
    restart: "always"
    volumes:
      - .:/picluster
      - ./docker-compose.config.json:/picluster/config.json
      - ./picluster-pm2.config-example.json:/picluster/picluster-pm2.config.json
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3003:3003"
    working_dir: /picluster
    command: ["sh", "-c", "set -e; printf 'http://mirror.clarkson.edu/alpine/edge/main\nhttp://mirror.clarkson.edu/alpine/edge/community' > /etc/apk/repositories; apk update; apk add --no-cache git python make g++ docker openrc procps; npm install -g pm2; npm install --production --unsafe-perm; (nohup dockerd &); sleep 20; pm2-docker start /picluster/picluster-pm2.config.json"]
    environment:
      COMPOSE_HTTP_TIMEOUT: 600
